const workoutTypes = [
  "",
  "Squat",
  "Lunges",
  "Deadlift",
  "Leg Press",
  "Leg Extension",
  "Leg Curl",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Hip Abductor",
  "Bench Press",
  "Chest Fly",
  "Push-up",
  "Pull-down",
  "Pull-up",
  "Bent-over Row",
  "Upright Row",
  "Shoulder Press",
  "Shoulder Fly",
  "Lateral Raise",
  "Shoulder Shrug",
  "Pushdown",
  "Tricep Extension",
  "Bicep Curl",
  "Sit-ups",
  "Russian Twist",
  "Leg Raise",
  "Back Extension",
  "Arnold Press",
].sort();

export default workoutTypes;
